In [1]:
from modules_main import *
# from old_modules.modules_fit import *
import json
import plotly.graph_objects as go
import numpy as np
import os
import pandas as pd

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Carga de dataframes con clasificación de ajuste posible/no posible.

In [4]:
pth=os.getcwd()
pthreg=pth+'/../data/lineas_completas/REG.csv'
reg_posible=pd.read_csv(pthreg)
pthvdi=pth+'/../data/lineas_completas/VDI.csv'
vdi_posible=pd.read_csv(pthvdi)
pthxin=pth+'/../data/lineas_completas/XIN.csv'
xin_posible=pd.read_csv(pthxin)
reg=reg_posible.loc[reg_posible['Reconstrucción']=='Posible','Vano']
vdi=vdi_posible.loc[vdi_posible['Reconstrucción']=='Posible','Vano']
xin=xin_posible.loc[xin_posible['Reconstrucción']=='Posible','Vano']

FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu-deduce/Projects/electra-ia/catenaria/notebooks/../data/lineas_completas/REG.csv'

Generación de ajustes

In [2]:
# from catenaria.notebooks.old_modules.modules_fit import *
import json
import os

pathdata2 = os.getcwd()+"/../data/lineas_completas/REG804.json"

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)

fulld=[data[i]['ID_VANO'] for i in range(len(data[0:10]))]
data, rmses, maxes, correlations=fit_plot_vano_group_2(data,sublist=fulld,plot_filter='good_fit',init=0,end=10,save=True,label='REG')#len(fulld)
#'bad_line_number', "bad_backing", bad_cluster, bad_line_number, bad_line_orientation, bad_fit, good_fit, 


Processing Vano 0

Reference G_13578462_13689863
First time 0.02900838851928711
Umbral de corte inferior detectado: -4587882.060554319
Umbral de corte superior detectado: -4587770.487469982
Third time 0.6834475994110107
Number of lines: 3


/home/ubuntu-deduce/Projects/electra-ia/.venv/lib/python3.10/site-packages/sklearn/manifold/_spectral_embedding.py:301: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


<class 'list'> <class 'numpy.ndarray'>
Fourth time 24.481866121292114
Fit error for z coordinate: 0.5142316554546188
Max error for z coordinate: 1.6257392055505848
Fit Pearson R for z coordinate: 0.8576513303950518
Fit Spearman R for z coordinate: 0.7493618909689919
Fit error for z coordinate: 0.9541308340617128
Max error for z coordinate: 2.1096028561695084
Fit Pearson R for z coordinate: 0.29938996558452013
Fit Spearman R for z coordinate: 0.09816938320399295
Fit error for z coordinate: 0.6254608621095724
Max error for z coordinate: 1.4987843700801409
Fit Pearson R for z coordinate: 0.7802555414536642
Fit Spearman R for z coordinate: 0.7397605944863794
Fifth time 0.018190860748291016
<class 'list'>
Sixth time 0.012041091918945312
{'G_13578462_13689863': (112.7467769530222, 111.94138938107537, 111.78383644209154, 39.932749382921344, 49.20762944663408, 15.110558431368789)} G_13578462_13689863
{'Reconstrucción': 'Posible', 'Flag': 'Tiene 3 o más conductores. Porcentaje de huecos: 7.80%'

/home/ubuntu-deduce/Projects/electra-ia/.venv/lib/python3.10/site-packages/sklearn/manifold/_spectral_embedding.py:301: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


KeyboardInterrupt: 

In [1]:
np.array(rmses).sum(axis = 1).mean(), np.array(maxes).max(axis = 1).mean(), np.array(correlations).mean(axis = 1).mean()

NameError: name 'np' is not defined

In [ ]:
print(res)

None


In [ ]:
np.unique(res.flag)

AttributeError: 'NoneType' object has no attribute 'flag'

In [ ]:
res.loc[res.flag=='empty',:].shape

(1, 3)

In [ ]:
res.loc[res.flag=='bad_cluster',:].shape

(11, 3)

In [ ]:
res.loc[res.flag=='bad_backing',:]

id         flag  line_number
13  G_13576748_13576812  bad_backing            0

In [ ]:
res.loc[res.flag=='good_fit',:].shape

(0, 3)

In [ ]:
from catenaria.notebooks.old_modules.modules_fit import *
import json
import os

pathdata2 = os.getcwd()+"/../data/lineas_completas/REG804.json"

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)
    
fulld=[data[i]['ID_VANO'] for i in range(len(data))]
res=fit_plot_vano_group(data,sublist=fulld,plot_filter='good_fit',init=0,end=len(fulld),save=True,label='REG')#len(fulld)

ModuleNotFoundError: No module named 'plotly'

In [ ]:
res.flag.value_counts()

flag
bad_cluster        87
bad_line_number    43
good_fit            9
empty               9
bad_backing         7
Name: count, dtype: int64

In [ ]:
res

NameError: name 'res' is not defined

In [ ]:
from catenaria.notebooks.old_modules.modules_fit import *
import json
import os

pathdata2 = os.getcwd()+"/../data/lineas_completas/XIN803.json"

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)
    

fulld=[data[i]['ID_VANO'] for i in range(len(data))]
res=fit_plot_vano_group(data,sublist=fulld,plot_filter=None,init=0,end=len(fulld),save=True,label='XIN')#len(fulld)
#'bad_line_number', "bad_backing", bad_cluster, bad_line_number, bad_line_orientation, bad_fit, good_fit, 


Processing Vano 0

Reference G_13645821_13645987
Umbral de corte superior detectado: 851254.4582811123
Number of lines: 3
(8040,)
[0 1 2]
(3,)

Processing Vano 1

Reference G_13645776_13645990
Umbral de corte inferior detectado: 4359432.5516279405
Umbral de corte superior detectado: 4359553.768260339
Number of lines: 3
(8546,)
[0 1 2]
(3,)

Processing Vano 2

Reference G_13645684_13645777
Umbral de corte inferior detectado: 251440.5701692517
Umbral de corte superior detectado: 251528.8044695908
Number of lines: 3
(5596,)
[0 1 2]
(3,)

Processing Vano 3

Reference G_13615863_13645824
Umbral de corte inferior detectado: -1043461.5826490528
Umbral de corte superior detectado: -1043410.1842453678
Number of lines: 3
(2878,)
[0 1 2]
(3,)

Processing Vano 4

Reference G_13645732_13645823
Umbral de corte inferior detectado: -1102312.024197021
Umbral de corte superior detectado: -1102159.7647004905
Number of lines: 3
(5945,)
[0 1 2]
(3,)

Processing Vano 5

Reference G_13499432_13645947
Umbral

/home/ubuntu-deduce/Projects/electra-ia/catenaria/notebooks/modules_fit.py:1102: RuntimeWarning: overflow encountered in cosh
  r=a * np.cosh((x - h) / a) + k


Number of lines: 3
(7305,)
[0 1 2]
(3,)

Processing Vano 81

Reference G_13597802_13645695
Umbral de corte inferior detectado: -4608989.422519232
Umbral de corte superior detectado: -4608786.053238494
Number of lines: 3
(6673,)
[0 1 2]
(3,)

Processing Vano 82

Reference G_13645789_13645916
Umbral de corte inferior detectado: -4609443.617692309
Umbral de corte superior detectado: -4609292.996995143
Number of lines: 3
(6045,)
[0 1 2]
(3,)

Processing Vano 83

Reference G_13645645_13645961
Umbral de corte superior detectado: 2332713.1473456793
Number of lines: 3
(7084,)
[0 1 2]
(3,)

Processing Vano 84

Reference G_13645844_13645845
Umbral de corte inferior detectado: -3638207.696426026
Umbral de corte superior detectado: -3638057.507208752
Number of lines: 3
(7277,)
[0 1 2]
(3,)

Processing Vano 85

Reference G_13645799_13645970
Umbral de corte inferior detectado: -4116335.2849874254
Umbral de corte superior detectado: -4116117.9422650244
Number of lines: 3
(7738,)
[0 1 2]
(3,)

Process

In [ ]:
from catenaria.notebooks.old_modules.modules_fit import *
import json
import os

pathdata2 = os.getcwd()+"/../data/lineas_completas/VDI711.json"

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)
    

fulld=[data[i]['ID_VANO'] for i in range(len(data))]
res=fit_plot_vano_group(data,sublist=fulld,plot_filter=None,init=0,end=len(fulld),save=True,label='VDI')#len(fulld)
#'bad_line_number', "bad_backing", bad_cluster, bad_line_number, bad_line_orientation, bad_fit, good_fit, 


Processing Vano 0

Reference C_13411888_13411889
Umbral de corte superior detectado: 2617144.872676384
Number of lines: 3

Processing Vano 1

Reference C_13412048_13412052
Umbral de corte inferior detectado: -3852391.868572913
Umbral de corte superior detectado: -3852312.239312542
Number of lines: 3

Processing Vano 2

Reference C_13412143_13412146
Umbral de corte superior detectado: 3910548.1512978827
Number of lines: 3

Processing Vano 3

Reference C_13412119_13412124
Umbral de corte inferior detectado: 3906191.4814983476
Umbral de corte superior detectado: 3906279.7072119163
Number of lines: 3

Processing Vano 4

Reference C_13412096_13412097
Umbral de corte inferior detectado: 3915462.50963112
Umbral de corte superior detectado: 3915544.4794009104
Number of lines: 3

Processing Vano 5

Reference C_13412120_13412145
Umbral de corte inferior detectado: 3919803.6859338717
Umbral de corte superior detectado: 3919897.814413377
Number of lines: 3

Processing Vano 6

Reference C_13412145

Recogida de ajustes y eliminación de outliers en parámetros

In [ ]:
import os
import json 
import numpy as np

pathdata2 = os.getcwd()+'/'+[el for el in os.listdir(os.getcwd()) if 'REG_resultado' in el][0]

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)

df_reg=data_catenaryparameters_to_df(data)


pathdata2 = os.getcwd()+'/'+[el for el in os.listdir(os.getcwd()) if 'VDI_resultado' in el][0]

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)

df_vdi=data_catenaryparameters_to_df(data)


pathdata2 = os.getcwd()+'/'+[el for el in os.listdir(os.getcwd()) if 'XIN_resultado' in el][0]

with open(pathdata2, 'r') as archivo:
    data = json.load(archivo)

df_xin=data_catenaryparameters_to_df(data)

0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1


In [ ]:
df_reg.shape

(155, 4)

In [ ]:
df_vdi.shape

(129, 4)

In [ ]:
df_xin.shape

(163, 4)

In [ ]:
df_reg=df_reg.dropna()
df_reg=df_reg.loc[df_reg['id'].isin(reg.to_list())]
df_vdi=df_vdi.dropna()
df_vdi=df_vdi.loc[df_vdi['id'].isin(vdi.to_list())]
df_xin=df_xin.dropna()
df_xin=df_xin.loc[df_xin['id'].isin(xin.to_list())]

In [ ]:
df_reg.shape

(65, 4)

In [ ]:
df_vdi.shape

(86, 5)

In [ ]:
df_xin.shape

(121, 4)

In [ ]:
df_reg=pretreatment_linegroup_from_json(df_reg)
df_vdi=pretreatment_linegroup_from_json(df_vdi)
df_xin=pretreatment_linegroup_from_json(df_xin)

In [ ]:
df_reg.shape

(45, 5)

In [ ]:
df_vdi.shape

(86, 5)

In [ ]:
df_xin.shape

(103, 5)